### PR TITLE
Adding models to Django admin UI

### LINKED ISSUE #31: Adding models to Django admin UI

### PR DESCRIPTION
**Pull request by Anas-mhameed**
resolve #31 

Registering the models in the Django admin UI

### CODE REVIEW

**Review by rawadabu — APPROVED** [review]
LGTM

**Review by Yarboa — APPROVED** [review]
LGTM. 
Note, since we reviewed all tests parts, although it is not a must for the Demo
I think you could propose a test to check it

**Review by Shalevro2 — APPROVED** [review]
LGTM

**Review by yaelnoyman1 — APPROVED** [review]
LGTM

**Pull request merged**
