### PR TITLE
Adding demo3 documents

### LINKED ISSUE #91: Add documentation files for Demo3
https://redhat-beyond.slack.com/archives/C049PAD7F7U/p1673171032424409

### PR DESCRIPTION
**Pull request by Shalevro2**
Adding video that Amit's created
Adding presentation and the content

Resolve #91

### CODE REVIEW

**Review by finziamit — APPROVED** [review]

**Review by rawadabu — APPROVED** [review]

**Review by Anas-mhameed — APPROVED** [review]

**Review by yaelnoyman1 — APPROVED** [review]

**Review by Yarboa — COMMENTED** [review]
I do not think it should be here, 
Consider maintainig a blog related to this repo, but not in it

**Comment by Shalevro2** [comment]
> I do not think it should be here, Consider maintainig a blog related to this repo, but not in it

You think we should delete all the documentation files ([This directory ](https://github.com/redhat-beyond/Smarticle/tree/main/documentations)) from this repo?

**Comment by yaelnoyman1** [comment]
> I do not think it should be here, Consider maintainig a blog related to this repo, but not in it

Hi, do you mean the video? or all the files of the demo?

**Comment by Anas-mhameed** [comment]
> I do not think it should be here, Consider maintainig a blog related to this repo, but not in it

can you explain @Yarboa ??

**Comment by Yarboa** [comment]
> > I do not think it should be here, Consider maintainig a blog related to this repo, but not in it
> 
> can you explain @Yarboa ??

1) You canhave the presentation as md file
2) I would skip hebrew presentation, at least try to upload it in markdown or image in md file

**Comment by avi-biton** [comment]
I agree with @Yarboa .
The hebrew presentation can be removed.
As for the other 2 presentations, its better to have them as MD files if possible.

**Comment by Shalevro2** [comment]
@avi-biton @Yarboa I deleted the Hebrew presentation.
I prefer to work some more important things instead of convert the presentation to MD file.

If the presentation must be a md file, maybe we can consider to close this PR .

**Comment by Yarboa** [comment]
> @avi-biton @Yarboa I deleted the Hebrew presentation. I prefer to work some more important things instead of convert the presentation to MD file.
> 
> If the presentation must be a md file, maybe we can consider to close this PR .

Its the group decision,
Either you think there should be a resource to that or not

**Comment by yaelnoyman1** [comment]
I also think it's not a top priority, so to close the pr right now and upload it only after demo 4

**Comment by Shalevro2** [comment]
> > @avi-biton @Yarboa I deleted the Hebrew presentation. I prefer to work some more important things instead of convert the presentation to MD file.
> > If the presentation must be a md file, maybe we can consider to close this PR .
> 
> Its the group decision, Either you think there should be a resource to that or not

In my opinion, we should not convert this presentation to an MD file.  I think that a lot of work was done on this presentation and we already have 2 presentations in our repository.

If we cannot reach an agreement I would convert this presentation after demo4.

**Comment by avi-biton** [comment]
I have no problem with merging it as it is.
@Yarboa Is it OK with you?

**Review by avi-biton — APPROVED** [review]

**Review by finziamit — COMMENTED** [review]
In my opinion if it requires modifications it's unnecessary, we have tasks with higher priority.

**Pull request merged**
