### PR TITLE
Adding documents

### LINKED ISSUE #64: Upload presentations
Upload presentations of demo1-2 and Smaritcle.pdf (from demo1) to doc' directory.

### PR DESCRIPTION
**Pull request by Shalevro2**
Adding logo files and demo's presentations

Creating folder for the diagrams

Resolve #64

### CODE REVIEW

**Review by yaelnoyman1 — COMMENTED** [review]
I think to keep only the logo we use.

**Comment by Shalevro2** [comment]
> I think to keep only the logo we use.
The 

In my opinion it is better to keep all the formats that Amit created.
 Each format have different uses.

WDYT?

**Review by finziamit — APPROVED** [review]
LGTM

**Review by yaelnoyman1 — APPROVED** [review]
LGTM

**Review by rawadabu — APPROVED** [review]

**Review by Yarboa — APPROVED** [review]
LGTM

**Pull request merged**
