### PR TITLE
Adding a Django development environment #7

### LINKED ISSUE #7: Setting up Pipenv and Django

### PR DESCRIPTION
**Pull request by Anas-mhameed**
resolve #7 
- Setup [Pipenv][1] to install and manage Django and other Python dependencies
- Bootstrapped an empty [Django][2] application
- Setup Vagrant to automatically bring our application up as well as make it accessible from a web browser

After running `vagrant up` the application can be accessed at:

> http://127.0.0.1:8000/

**Note:** Most changes had been auto-generated, only `Vagrantfile` has been edited manually.

### CODE REVIEW

**Comment by avi-biton** [comment]
When you use the following syntax:
`Setup [Pipenv][1]` you need to supply the reference at the end of the text.

For example:
```
some text
Setup [Pipenv][1]
some text

[1]: https://github.com/pypa/pipenv
```

The [1] in the message refers to the [1] link at the end of the message

**Comment by Anas-mhameed** [comment]
I fixed it .

**Comment by Yarboa** [comment]
> resolve #7
> 
> * Setup [Pipenv][1] to install and manage Django and other Python dependencies
> * Bootstrapped an empty [Django][2] application
> * Setup Vagrant to automatically bring our application up as well as make it accessible from a web browser
> 
> After running `vagrant up` the application can be accessed at:
> 
> > http://127.0.0.1:8000/
> 
> **Note:** Most changes had been auto-generated, only `Vagrantfile` has been edited manually.

@Anas-mhameed please refer first line in comment
Added resolve and Issue number

**Review by Yarboa — APPROVED** [review]
LGTM

**Comment by avi-biton** [comment]
LGTM

**Review by avi-biton — APPROVED** [review]

**Pull request merged**
