### PR TITLE
Adding Diagrams files

### LINKED ISSUE #18: Create DFD and ERD
- Create and upload the ERD 
- Create and upload the DFD

### PR DESCRIPTION
**Pull request by Shalevro2**
Create DRAWIO_INFO.md file- description about drawio files

Adding ERD-smarticle.jpg- ERD as jpg file
Adding ERD-smarticle.drawio- ERD as .drawio file

Adding Smarticle-DFD.png- DFD as png file
Adding Smarticle-DFD.drawio- DFD as .drawio file

Resolve #18

### CODE REVIEW

**Review by rawadabu — APPROVED** [review]

**Review by yaelnoyman1 — APPROVED** [review]

**Review by Yarboa — COMMENTED** [review]
Questions
1) Why Guest readers should have interaction with Users data?
2) Can guest insert article data? 
3) In that case what is the difference between Guest/Users?

Does the only difference between Guest and User is:
User is a Guest who did sign up? 
User is a Guest which is logged in?

**Comment by Shalevro2** [comment]
> Questions
> 
> 1. Why Guest readers should have interaction with Users data?
> 2. Can guest insert article data?
> 3. In that case what is the difference between Guest/Users?
> 
> Does the only difference between Guest and User is: User is a Guest who did sign up? User is a Guest which is logged in?


1. The Guest is a unregistered user, he can to signup to the app.
2. No, he can to read or search article.
3. User can create, update and delete his articles while Guest can only to read articles of other users. Also User can submit a like to article, while Guest cannot.

**Comment by Anas-mhameed** [comment]
User vs Guest
User has an account in our app , but guest doesn't.
User can do all CRUD operation with the articls, the Guest can just read the articls.
but Guest can also become a User via signing up in the app.
when you see in the DFD Guest "insert User data" , we intent that the Guest is sending his data in order to singup in the app.
when you see Guest "insert article data", we intent that the Guest chose an article in order to read it ,so the System is receiving the article data in order to contact with the database to retrive the article and display it to the Guest (we have decided that we don't want to display the hole article to the user until he click on it ).

**Review by finziamit — APPROVED** [review]

**Review by NitzanMordhai — COMMENTED** [review]
In ERD, Article have 2 subjects?

**Comment by Shalevro2** [comment]
> In ERD, Article have 2 subjects?

No, it is a mistake. 
I fixed that on [e428034](https://github.com/redhat-beyond/Smarticle/pull/19/commits/e42803492bdc2a08dc047ab8598c7827f729655f)

**Comment by Yarboa** [comment]
> > Questions
> > 
> > 1. Why Guest readers should have interaction with Users data?
> > 2. Can guest insert article data?
> > 3. In that case what is the difference between Guest/Users?
> > 
> > Does the only difference between Guest and User is: User is a Guest who did sign up? User is a Guest which is logged in?
> 
> 1. The Guest is a unregistered user, he can to signup to the app.
> 2. No, he can to read or search article.
> 3. User can create, update and delete his articles while Guest can only to read articles of other users. Also User can submit a like to article, while Guest cannot.

Thanks
so basically, there is no direct entity Guest.

IIUC, there are few data flows which allowed for non registered and addition for registered users.
Do you think less complexity could be presented once you had isRegisteredUser? 
This just take WebUSER ApiUSER  
https://cloud.gov/assets/img/example-diagram-1.pdf

Do you think there is a need for GuestWeb and UserWeb?

**Review by Anas-mhameed — APPROVED** [review]
LGTM

**Pull request merged**
