### PR TITLE
Fix the style of the web site

### LINKED ISSUE #76: Improve and fix the styles
When #73 #70 will be merge, improve and fix the styles before demo3.
Also consider to change the path of search_article.html

### PR DESCRIPTION
**Pull request by yaelnoyman1**
Resolve #76

### CODE REVIEW

**Review by finziamit — APPROVED** [review]
LGTM

consider changing the path of search_article.html as said in issue #76

**Review by Yarboa — APPROVED** [review]

**Review by rawadabu — APPROVED** [review]

**Review by Anas-mhameed — COMMENTED** [review]
Did you check all components height ?? (footer)
footer should stick at the bottom of the page (we did have a problem before)

**Comment by Anas-mhameed** [comment]
what bg-color you choose to use ??

**Comment by yaelnoyman1** [comment]
> 

The putter is almost in good condition, some pages have a small space Any idea how to fix this?

**Comment by Anas-mhameed** [comment]
> 

try this => in footer css {position: fixed;}
if not try to change the main element height

**Comment by Shalevro2** [comment]
> LGTM
> 
> consider changing the path of search_article.html as said in issue #76

In addition to this comment.

@Anas-mhameed What do you think about deleting the templates/projboard folder? And just keep it templates/searchArticle

**Comment by Anas-mhameed** [comment]
> > LGTM
> > consider changing the path of search_article.html as said in issue #76
> 
> In addition to this comment.
> 
> @Anas-mhameed What do you think about deleting the templates/projboard folder? And just keep it templates/searchArticle

it's ok, we can do that

**Comment by Anas-mhameed** [comment]
@yaelnoyman1  in search_article.html there is an issue with the search bar height, fix that too.

**Comment by yaelnoyman1** [comment]
> @yaelnoyman1 in search_article.html there is an issue with the search bar height, fix that too.

Yes, now it makes sense to me why the footer is only good there

**Comment by yaelnoyman1** [comment]
> what bg-color you choose to use ??

look in base.css

**Comment by yaelnoyman1** [comment]
> in search_article.html there is an issue with the search bar height, fix that too.

I fixed it already

**Comment by yaelnoyman1** [comment]
> if not try to change the main element height

Now I see that in the display of the computer screen the footer is good
but in the display of a larger screen there is a small space below

but on the search_article page it's good
Can you explain to me what you did there?

**Comment by yaelnoyman1** [comment]
> LGTM
> 
> consider changing the path of search_article.html as said in issue #76

done

**Review by Shalevro2 — APPROVED** [review]
LGTM

**Review by Anas-mhameed — APPROVED** [review]
LGTM

**Review by avi-biton — APPROVED** [review]
LGTM

**Pull request merged**
